### ISSUE TITLE
Add postgres adminer image

### ISSUE THREAD

**Issue by repejota** [vtalks/deploy#1]
## Description

Add postgres adminer image (only in development) to docker compose

```
adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
```

https://hub.docker.com/_/postgres/
